#+TITLE: macroexp-view

* NAME

macroexp-view - Convenience commands for quickly and easily viewing macro expansions.

* SYNOPSIS

#+BEGIN_SRC emacs-lisp
  (require 'macroexp-view)
  
  (add-hook 'emacs-lisp-mode-hook 'macroexp-view-minor-mode)
  (add-hook 'ielm-mode-hook 'macroexp-view-minor-mode)
#+END_SRC

* DESCRIPTION

** =mv-macroexpand-sexp-at-point (&optional all)=

Macroexpand the S-expression at point, displaying the result in a
different byffer.  Prefix argument =all= means expand all subforms
too, as with =macroexpand-all=.  Return =t= if expansion succeeds,
=nil= otherwise.

** =mv-macroexpand-sexp-at-point-inline=

Like =mv-macroexpand-sexp-at-point=, except replace the unexpanded
form with the expanded form.

** =macroview-expand-minor-mode=

A minor mode that binds the above functions to =C-c m= and =C-c M-m=,
respectively.

* AUTHOR

Nathan Trapuzzano =<nbtrap@nbtrap.com>=

* LICENSE

This program is free software: you can redistribute it and/or modify it under
the terms of the GNU General Public License as published by the Free Software
Foundation, either version 3 of the License, or (at your option) any later
version.

This program is distributed in the hope that it will be useful, but WITHOUT
ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more
details.

You should have received a copy of the GNU General Public License along with
this program.  If not, see [[http://www.gnu.org/licenses/]].
